# Deploy static site to configured host
name: STATICSITE-VERCEL-DEPLOYMENT

on:
  workflow_call:
    inputs:
      artefact-ref:
        required: true
        type: string
      vercel-project-id:
        required: true
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: none

# Allow one concurrent deployment
concurrency:
  group: 'deployment-vercel'
  cancel-in-progress: false

jobs:

  deploy-vercel:
    name: 🚀 Vercel
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: none
    env:
      VERCEL_PROJECT_ID: ${{ inputs.vercel-project-id }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:

      - name: Check variable exist
        if: ${{ env.VERCEL_PROJECT_ID == '' }}
        run: |
          echo "### 🚨 ERROR" >> $GITHUB_STEP_SUMMARY
          echo "Missing VERCEL_PROJECT_ID" >> $GITHUB_STEP_SUMMARY
          exit 1

      - name: Check secret exist
        if: ${{ env.VERCEL_ORG_ID == ''}}
        run: |
          echo "### 🚨 ERROR" >> $GITHUB_STEP_SUMMARY
          echo "Missing VERCEL_ORG_ID" >> $GITHUB_STEP_SUMMARY
          exit 1

      - name: Check secret exist
        if: ${{ env.VERCEL_TOKEN == '' }}
        run: |
          echo "### 🚨 ERROR" >> $GITHUB_STEP_SUMMARY
          echo "Missing VERCEL_TOKEN" >> $GITHUB_STEP_SUMMARY
          exit 1

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Vercel CLI
        run: npm install vercel@latest

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artefact-ref }}
          path: dist
      
      - name: Change Dir
        run: cd dist

      - name: Vercel Pull
        run: npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Vercel Build
        run: npx vercel build --prod --token=$VERCEL_TOKEN

      - name: Vercel Deploy
        run: npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN